const SOLUTION_WORDS: string[] = [
  "about","above","abuse","actor","acute","admit","adopt","adult","after","again",
  "agent","agree","ahead","alarm","album","alert","alien","align","alive","alley",
  "allow","alone","along","alter","ample","angel","anger","angle","angry","anime",
  "ankle","apart","apple","apply","arena","argue","arise","armor","array","arrow",
  "asset","atlas","avoid","awake","award","aware","awful","bacon","badge","badly",
  "baker","basic","basis","batch","beach","beard","beast","begun","being","below",
  "bench","berry","birth","black","blade","blame","blank","blast","blaze","bleed",
  "blend","bless","blind","block","blood","bloom","blown","board","boast","bonus",
  "boost","booth","bound","brain","brand","brave","bread","break","breed","brick",
  "bride","brief","bring","broad","broke","brook","brown","brush","buddy","build",
  "built","bunch","burst","buyer","cabin","cable","camel","candy","cargo","carry",
  "catch","cause","cease","chain","chair","chalk","champ","chaos","charm","chart",
  "chase","cheap","cheat","check","cheek","cheer","chess","chest","chief","child",
  "chill","china","chunk","civic","civil","claim","clash","class","clean","clear",
  "clerk","click","cliff","climb","cling","clock","clone","close","cloth","cloud",
  "coach","coast","color","comet","comic","coral","could","count","court","cover",
  "crack","craft","crane","crash","crazy","cream","creek","crime","cross","crowd",
  "crown","cruel","crush","curve","cycle","daily","dance","death","debug","debut",
  "decay","decor","decoy","delay","delta","dense","depot","depth","derby","devil",
  "diary","dirty","disco","ditch","dizzy","dodge","donor","doubt","dough","draft",
  "drain","drama","drank","drape","drawn","dream","dress","drift","drill","drink",
  "drive","drone","drown","drunk","dryer","dummy","dusty","dutch","dwarf","dwell",
  "eager","eagle","early","earth","eight","elect","elite","email","ember","empty",
  "enemy","enjoy","enter","entry","equal","error","essay","evade","event","every",
  "exact","exile","exist","extra","fable","faith","false","fancy","fatal","fault",
  "feast","fence","fetch","fever","fiber","field","fifth","fifty","fight","final",
  "first","fixed","flame","flash","fleet","flesh","flick","flight","float","flock",
  "flood","floor","flora","flour","fluid","flush","focal","focus","force","forge",
  "forth","forum","found","frame","frank","fraud","fresh","front","frost","fruit",
  "fully","giant","given","glass","globe","glory","glove","going","grace","grade",
  "grain","grand","grant","graph","grasp","grass","grave","great","green","greet",
  "grief","grill","grind","groan","gross","group","grove","grown","guard","guess",
  "guest","guide","guilt","gut","habit","happy","harsh","heart","heavy","hedge",
  "heist","hello","hence","herbs","hinge","hobby","honor","horse","hotel","house",
  "human","humid","humor","hurry","hyper","ideal","image","imply","inbox","index",
  "indie","inner","input","issue","ivory","jewel","joint","joker","judge","juice",
  "juicy","jumbo","knock","known","label","large","laser","later","laugh","layer",
  "learn","lease","least","leave","legal","lemon","level","lever","light","limit",
  "linen","liner","logic","loose","lover","lower","loyal","lucky","lunar","lunch",
  "macro","magic","major","maker","manor","maple","march","match","mayor","media",
  "mercy","merge","merit","metal","meter","micro","midst","might","minor","minus",
  "model","money","month","moral","mount","mouse","mouth","movie","music","naive",
  "nasty","naval","nerve","never","newly","night","noble","noise","north","noted",
  "novel","nurse","nylon","ocean","offer","often","olive","onset","opera","orbit",
  "organ","other","outer","owing","oxide","ozone","paint","panel","panic","paper",
  "party","pasta","paste","patch","pause","peace","peach","pearl","penny","perch",
  "phase","phone","photo","piano","piece","pilot","pinch","pixel","pizza","place",
  "plain","plane","plant","plate","plaza","plead","plumb","plume","plump","point",
  "polar","porch","poser","pound","power","press","price","pride","prime","print",
  "prior","prize","probe","proof","proud","prove","psalm","pulse","punch","pupil",
  "purse","push","queen","query","quest","quick","quiet","quite","quota","quote",
  "radar","radio","raise","rally","range","rapid","ratio","reach","realm","rebel",
  "reign","relax","repay","reply","rider","ridge","rifle","right","rigid","risky",
  "rival","river","robin","robot","rocky","roman","roost","rough","round","route",
  "royal","rugby","ruler","rural","sadly","saint","salad","sauce","scale","scare",
  "scene","scope","score","scout","scrap","seize","sense","serve","setup","seven",
  "shade","shake","shall","shame","shape","share","sharp","sheep","sheer","sheet",
  "shelf","shell","shift","shine","shirt","shock","shoot","shore","short","shout",
  "sight","sigma","since","sixth","sixty","sized","skill","skull","slash","slate",
  "slave","sleep","slice","slide","slope","smart","smell","smile","smoke","snake",
  "solar","solid","solve","sorry","sound","south","space","spare","spark","speak",
  "spear","speed","spend","spice","spine","spite","split","spoke","spoon","sport",
  "spray","squad","stack","staff","stage","stain","stake","stale","stall","stamp",
  "stand","stark","start","state","stays","steal","steam","steel","steep","steer",
  "stern","stick","stiff","still","stock","stone","stood","store","storm","story",
  "stove","strap","straw","stray","strip","stuck","study","stuff","style","sugar",
  "suite","super","surge","swamp","swear","sweep","sweet","swept","swift","swing",
  "sword","swore","sworn","syrup","table","taste","teach","teeth","theme","thick",
  "thief","thing","think","third","thorn","those","three","threw","throw","thumb",
  "tiger","tight","timer","title","toast","today","token","topic","total","tough",
  "towel","tower","toxic","trace","track","trade","trail","train","trait","trash",
  "treat","trend","trial","tribe","trick","tried","troop","trout","truck","truly",
  "trump","trunk","trust","truth","tumor","tuner","twice","twist","ultra","uncle",
  "under","union","unity","until","upper","upset","urban","usage","usual","utter",
  "valid","value","vault","verse","vigor","vinyl","viral","virus","visit","vital",
  "vivid","vocal","vodka","voice","voter","wagon","waste","watch","water","weary",
  "weave","weird","wheat","wheel","where","which","while","whole","whose","width",
  "witch","woman","world","worry","worst","worth","would","wound","wrath","write",
  "wrote","yacht","yield","young","youth","zebra"
];

const VALID_GUESSES: Set<string> = new Set([
  ...SOLUTION_WORDS,
  "aahed","aalii","aback","abase","abash","abate","abbey","abbot","abhor","abide",
  "ablaze","abort","abound","abrupt","absurd","abyss","ached","acids","acorn","acres",
  "acted","adapt","added","adept","adorn","adore","affix","afoot","agape","agate",
  "agile","aging","aglow","agony","agree","aided","aimed","aisle","algae","alibi",
  "alien","align","alike","allot","alloy","aloft","alpha","altar","amaze","amber",
  "amend","amino","among","ample","amuse","angel","angle","annex","antic","anvil",
  "aorta","aping","apple","aptly","arbor","ardor","arena","argue","arise","armor",
  "aroma","arose","array","arson","ashen","aside","asked","asset","atoll","atone",
  "attic","audio","audit","augur","aunts","avian","avoid","await","awash","axial",
  "axiom","azure","badge","badly","bagel","baggy","baked","balls","bands","banjo",
  "banks","baron","bases","basic","basin","basis","batch","bathe","batty","bayou",
  "beach","beads","beams","beans","bears","beast","beats","beech","beefs","beers",
  "began","begin","begun","being","bells","belly","below","belts","bench","berry",
  "bible","bikes","billy","bingo","biome","birds","birth","bison","black","blade",
  "blame","bland","blank","blare","blast","blaze","bleak","bleat","bleed","blend",
  "bless","blimp","blind","bliss","blitz","bloat","block","bloke","blond","blood",
  "bloom","blown","blues","bluff","blunt","blurt","blush","board","boats","bobby",
  "bogus","boils","bolts","bombs","bonds","bones","bonus","books","boost","boots",
  "booze","boozy","borax","bored","borne","bosom","bossy","botch","bound","bough",
  "bowel","boxer","boxes","brace","braid","brain","brake","brand","brash","brass",
  "brave","brawn","bread","break","breed","brick","bride","brief","brine","bring",
  "brink","briny","brisk","broad","broil","broke","brood","brook","broom","broth",
  "brown","brush","brunt","brute","buddy","budge","buggy","build","built","bulge",
  "bulky","bully","bunch","bunny","burst","buses","bushy","buyer","bytes","cabal",
  "cabin","cable","cadet","caged","cakes","calls","camel","camps","candy","canes",
  "caped","carat","cards","cargo","carol","carry","carve","catch","cater","cause",
  "caves","cedar","chain","chair","chalk","champ","chant","chaos","charm","chart",
  "chase","cheap","cheat","check","cheek","cheer","chess","chest","chick","chief",
  "child","chile","chill","chimp","china","chips","choir","chord","chore","chose",
  "chunk","churn","cider","cigar","cinch","circa","civic","civil","claim","clamp",
  "clang","clank","clash","clasp","class","claws","clean","clear","clerk","click",
  "cliff","climb","cling","clink","cloak","clock","clone","close","cloth","cloud",
  "clout","clown","clubs","cluck","clued","clues","clung","coach","coals","coast",
  "cocoa","coded","codes","coils","coins","colic","colon","color","comet","comic",
  "comma","conch","condo","cones","coral","cords","cores","corgi","corny","couch",
  "could","count","coupe","court","cover","covet","crack","craft","cramp","crane",
  "crank","crash","crass","crate","crave","crawl","craze","crazy","creak","cream",
  "creek","creep","crest","crews","crimp","crisp","croak","crock","cross","crowd",
  "crown","crude","cruel","crush","crust","cubic","cumin","curse","curve","cycle",
  "cynic","daddy","daily","dairy","daisy","dance","dated","datum","dealt","death",
  "debit","debug","debut","decal","decay","decor","decoy","decry","defer","deity",
  "delay","delta","delve","demon","denim","dense","depot","depth","derby","desks",
  "detox","deuce","devil","diary","digit","dimly","diner","dingy","dirty","disco",
  "ditch","ditty","diver","dizzy","dodge","dogma","doing","dolls","donor","donut",
  "doors","dopey","doses","doubt","dough","dowdy","downs","dozed","draft","drain",
  "drake","drama","drank","drape","drawl","drawn","dread","dream","dress","dried",
  "drift","drill","drink","drive","droit","droll","drone","drool","droop","drops",
  "dross","drove","drown","drums","drunk","dryer","dryly","ducal","dully","dummy",
  "dunce","dunes","dunks","dusty","dutch","dwarf","dwell","dwelt","dying","eager",
  "eagle","early","earth","easel","eaten","eater","ebbed","ebony","edged","edges",
  "edict","eight","eject","elbow","elder","elect","elfin","elite","elope","elude",
  "email","ember","emcee","emote","empty","enact","ended","endow","enemy","enjoy",
  "ennui","ensue","enter","entry","envoy","epoch","equal","equip","erase","erode",
  "error","erupt","essay","ether","ethic","evade","event","every","evict","evoke",
  "exact","exalt","exams","excel","exert","exile","exist","expat","expel","extra",
  "exude","exult","fable","faced","facet","facts","fairy","faith","false","famed",
  "fancy","fangs","fatal","fatty","fault","fauna","feast","feats","fence","feral",
  "ferry","fetal","fetch","fetid","feud","fever","fewer","fiber","fibre","field",
  "fiend","fiery","fifth","fifty","fight","filth","final","finch","finds","finer",
  "fired","fires","firms","first","fishy","fixed","flair","flake","flaky","flame",
  "flank","flare","flash","flask","fleet","flesh","flick","flier","fling","flint",
  "float","flock","flood","floor","flora","floss","flour","flout","flows","fluid",
  "fluke","flung","flush","flute","focal","focus","foggy","folly","fonts","foods",
  "force","forge","forms","forth","forty","forum","fossil","found","fox","foyer",
  "frail","frame","frank","fraud","freak","freed","fresh","friar","fried","frill",
  "frisk","fritz","frock","front","frost","froze","fruit","fully","fungi","funky",
  "funny","furor","furry","fused","fussy","fuzzy","gauge","gaunt","gauze","gavel",
  "gawky","giddy","given","gizmo","gland","glare","glass","glaze","gleam","glean",
  "glide","glint","gloat","globe","gloom","glory","gloss","glove","glued","gnash",
  "goats","going","golly","goods","goody","goofy","goose","gorge","gotta","gouge",
  "gourd","grace","grade","graft","grail","grain","grand","grant","grape","graph",
  "grasp","grass","grate","grave","gravy","graze","great","greed","green","greet",
  "grief","grill","grime","grimy","grind","gripe","grits","groan","groom","grope",
  "gross","group","grout","grove","growl","grown","gruel","gruff","grunt","guard",
  "guava","guess","guest","guide","guild","guilt","guise","gulch","gummy","gusty",
  "gypsy","habit","hands","handy","happy","hardy","harsh","haste","hasty","hatch",
  "haunt","haven","hazel","heads","heart","heave","heavy","hedge","heels","hefty",
  "heirs","heist","hello","hence","herbs","heron","hilly","hinge","hippo","hitch",
  "hobby","homer","homes","honey","honor","hooks","hoped","horns","horse","hotel",
  "hound","hours","house","hover","hulks","human","humid","humor","humps","hurry",
  "hyena","hyper","icing","ideal","idiot","idyll","igloo","image","imbue","impel",
  "imply","inbox","incur","index","indie","inept","inert","infer","ingot","inner",
  "input","inter","intro","ionic","irate","irony","issue","ivory","jazzy","jelly",
  "jewel","jiffy","jimmy","joker","jolly","joust","judge","juice","juicy","jumbo",
  "jumps","junco","juror","kayak","kebab","keyed","khaki","kinky","knack","knave",
  "knead","kneel","knelt","knife","knobs","knock","knoll","knots","known","kudos",
  "label","labor","laced","laden","ladle","lager","lance","lanes","lapse","large",
  "larva","laser","latch","later","latex","laugh","lawns","layer","leads","leafy",
  "leaky","leaps","learn","lease","leash","least","leave","ledge","leech","legal",
  "lemon","lemur","level","lever","lexis","liens","light","lilac","limbo","limit",
  "linen","liner","lingo","links","lions","lists","liter","lived","liver","llama",
  "loads","loafs","loamy","loans","lobby","local","locks","locus","lodge","lofty",
  "logic","looks","loopy","loose","lords","loser","lousy","loved","lover","lower",
  "loyal","lucid","lucky","lumen","lumps","lumpy","lunar","lunch","lunge","lurch",
  "lusty","lyric","macro","mafia","magic","magma","major","maker","males","malls",
  "mango","mania","manic","manor","maple","march","marks","marsh","masks","match",
  "mated","mates","maxim","mayor","mealy","means","meaty","medal","media","medic",
  "meets","melon","mercy","merge","merit","merry","messy","metal","meter","micro",
  "midst","might","milky","mills","mimic","mince","minds","miner","mines","minor",
  "minus","mirth","miser","misty","mitre","mixer","moans","moats","model","modem",
  "mogul","moist","molar","moldy","money","monks","month","moody","moose","moral",
  "moron","morph","mossy","motel","moths","motor","motto","mould","mound","mount",
  "mourn","mouse","mousy","mouth","moved","mover","moves","movie","mower","mucus",
  "muddy","mules","multi","mummy","munch","mural","murky","mushy","music","musky",
  "musty","naive","nanny","nasal","nasty","natal","naval","navel","nerdy","nerve",
  "never","newly","nexus","niche","night","ninja","noble","nobly","noise","noisy",
  "nomad","north","nosed","notch","noted","novel","nudge","nurse","nutty","nylon",
  "oaken","oasis","occur","ocean","oddly","odder","offal","offer","often","oinks",
  "older","olive","omega","onset","opens","opera","opted","optic","orbit","order",
  "organ","other","otter","ought","ounce","outdo","outer","ovary","ovate","owing",
  "owned","owner","oxide","ozone","paced","packs","paddy","pagan","pages","pains",
  "paint","pairs","paler","palms","palsy","panda","panel","panic","pansy","pants",
  "paper","parks","parts","party","pasta","paste","patch","patio","pause","paved",
  "peace","peach","peaks","pearl","pears","pecan","pedal","penal","pence","penny",
  "perch","peril","perks","perky","pesky","petal","petty","phase","phone","photo",
  "piano","picky","piece","piggy","piles","pilot","pinch","pines","pinky","pinto",
  "pious","pipes","pitch","pixel","pixie","pizza","place","plaid","plain","plane",
  "plank","plans","plant","plate","playa","plaza","plead","pleat","plied","plier",
  "plods","plots","plows","pluck","plugs","plumb","plume","plump","plums","plunge",
  "plunk","plush","pluto","poach","poems","poets","point","poise","poker","polar",
  "poles","polyp","ponds","pools","porch","pores","ports","poser","poses","posts",
  "pouch","poult","pound","pours","power","prank","prawn","prays","press","prexy",
  "price","prick","pride","pried","pries","prime","print","prior","prism","privy",
  "prize","probe","prods","prone","prong","proof","prose","proud","prove","prowl",
  "prude","prune","psalm","pubic","pudgy","pulls","pulps","pulse","pumps","punch",
  "pupil","puppy","purge","purse","pushy","putty","pygmy","quack","quaff","quail",
  "qualm","quart","quasi","queen","queer","query","quest","queue","quick","quiet",
  "quill","quilt","quirk","quota","quote","rabbi","rabid","racer","racks","radar",
  "radii","radio","radon","rafts","raids","rails","rainy","raise","raked","rally",
  "ranch","range","ranks","rapid","ratio","raven","rayon","razor","reach","react",
  "reads","ready","realm","reams","reaps","rebel","rebus","recap","recess","recon",
  "redis","reedy","reefs","reeks","regal","reign","reins","relax","relay","relic",
  "remit","remix","renal","renew","repay","repel","reply","rerun","reset","resin",
  "rests","retro","retry","reuse","revel","rider","ridge","rifle","right","rigid",
  "rings","rinse","riots","risen","risky","rivet","roach","roads","roams","roars",
  "roast","robes","robin","robot","rocks","rocky","rodeo","rogue","roles","rolls",
  "roman","roost","roots","roped","ropes","roses","rotor","rouge","rough","round",
  "rouse","route","rover","royal","rugby","ruins","ruled","ruler","rules","rumba",
  "rumor","rupee","rural","rusty","sadly","safer","saint","salad","sales","salon",
  "salsa","salty","salve","salvo","sands","sandy","saner","satin","sauce","saucy",
  "sauna","saute","saved","savor","savvy","scale","scalp","scald","scamp","scams",
  "scant","scare","scarf","scary","scene","scent","scold","scone","scoop","scope",
  "score","scorn","scout","scowl","scram","scrap","scree","screw","scrub","seams",
  "seeds","seedy","seeks","seems","seize","sense","sepia","serif","serve","setup",
  "seven","sever","shade","shady","shaft","shake","shaky","shall","shame","shape",
  "shard","share","shark","sharp","shawl","shear","sheds","sheen","sheep","sheer",
  "sheet","shelf","shell","shift","shine","shiny","shire","shirt","shock","shone",
  "shook","shoot","shops","shore","short","shots","shout","shove","shown","shows",
  "showy","shrub","shrug","shuck","shunt","sides","siege","sieve","sight","sigma",
  "silks","silky","silly","since","sinew","siren","sixth","sixty","sized","sizes",
  "skate","skied","skill","skimp","skins","skips","skirt","skull","skunk","slack",
  "slain","slang","slant","slate","slave","sleek","sleep","sleet","slept","slice",
  "slide","slime","slimy","sling","slink","slope","slots","sloth","slump","slung",
  "slunk","slurp","smart","smash","smear","smell","smelt","smile","smirk","smith",
  "smock","smoke","smoky","snack","snail","snake","snare","snarl","sneak","sneer",
  "snide","sniff","snore","snort","snout","snowy","snubs","snuck","snuff","soapy",
  "sober","solar","solid","solve","sonic","sorry","sorts","souls","sound","south",
  "space","spade","spare","spark","spasm","spawn","speak","spear","speck","specs",
  "speed","spell","spend","spent","spice","spicy","spied","spiel","spike","spill",
  "spine","spite","split","spoke","spoof","spook","spool","spoon","spore","sport",
  "spots","spray","spree","sprig","spunk","spurt","squad","squat","squid","stack",
  "staff","stage","staid","stain","stair","stake","stale","stalk","stall","stamp",
  "stand","stank","stare","stark","start","stash","state","stave","stays","steak",
  "steal","steam","steed","steel","steep","steer","stems","steno","stern","stew",
  "stick","stiff","still","sting","stink","stint","stock","stoic","stoke","stole",
  "stomp","stone","stood","stool","stoop","stops","store","stork","storm","story",
  "stout","stove","strap","straw","stray","strip","strum","strut","stuck","study",
  "stuff","stump","stung","stunk","stunt","style","suave","sugar","suite","sulky",
  "sunny","super","surge","sushi","swamp","swank","swaps","swarm","swath","swear",
  "sweat","sweep","sweet","swell","swept","swift","swill","swine","swing","swipe",
  "swirl","swish","swoon","swoop","sword","swore","sworn","swung","syrup","tabby",
  "table","taboo","tacit","tacky","taffy","taint","taken","tales","talks","tally",
  "talon","tamed","tangy","tapir","tardy","tasks","taste","tasty","tatty","taunt",
  "taxed","taxes","taxis","teach","tears","teary","tease","teens","teeth","tempo",
  "tends","tenor","tense","tenth","tepid","terms","terse","tests","thank","theft",
  "their","theme","thick","thief","thigh","thing","think","third","thorn","those",
  "three","threw","throb","throw","thrum","thumb","thump","tiara","tidal","tided",
  "tiger","tight","tiled","tilts","timed","timer","timid","tinge","tipsy","tired",
  "titan","title","toast","today","token","tolls","tombs","toner","tones","tongs",
  "topic","topaz","torch","toted","total","totem","touch","tough","tours","towel",
  "tower","towns","toxic","trace","track","tract","trade","trail","train","trait",
  "tramp","trash","trawl","tread","treat","trees","trend","triad","trial","tribe",
  "trick","tried","trims","tripe","trite","troll","troop","trope","troth","trout",
  "trove","truce","truck","truly","trump","trunk","truss","trust","truth","tubes",
  "tulip","tumor","tuned","tuner","turbo","turns","tutor","twang","tweak","tweed",
  "tweet","twice","twigs","twill","twine","twins","twirl","twist","tying","udder",
  "ulcer","ultra","umbra","uncut","under","undid","undue","unfit","unify","union",
  "unite","units","unity","unlit","until","unzip","upper","upset","urban","usage",
  "usher","using","usual","utter","udder","vague","valid","valor","value","valve",
  "vapor","vault","vaunt","vegan","veils","veins","venue","verge","verse","vigor",
  "viper","viral","virus","visor","visit","vista","vital","vivid","vocal","vodka",
  "vogue","voice","voila","voter","vouch","vowel","vulva","wacky","waded","wager",
  "wages","wagon","waist","waits","waked","walks","walls","waltz","wands","wants",
  "wards","waste","watch","water","waved","waver","waves","waxed","weary","weave",
  "wedge","weeds","weedy","weeks","weigh","weird","wells","welsh","whale","wheat",
  "wheel","where","which","while","whine","whiny","whips","whirl","whisk","white",
  "whole","whose","widen","wider","widow","width","wield","winds","windy","wines",
  "wings","wiped","wiper","wired","wires","witch","woman","women","woods","woody",
  "words","wordy","works","world","worms","worry","worse","worst","worth","would",
  "wound","wrack","wrath","wreak","wreck","wring","wrist","write","wrong","wrote",
  "yacht","yearn","yeast","yield","young","yours","youth","zebra","zesty","zilch",
  "zonal","zones"
]);

export class WordService {
  private solutions: string[];
  private validGuesses: Set<string>;
  private usedWords: Set<string>;

  constructor() {
    this.solutions = SOLUTION_WORDS;
    this.validGuesses = VALID_GUESSES;
    this.usedWords = new Set();
  }

  isValidGuess(word: string): boolean {
    return word.length === 5 && this.validGuesses.has(word.toLowerCase());
  }

  getRandomSolution(): string {
    const available = this.solutions.filter((w) => !this.usedWords.has(w));
    if (available.length === 0) {
      this.usedWords.clear();
      return this.solutions[Math.floor(Math.random() * this.solutions.length)];
    }
    const word = available[Math.floor(Math.random() * available.length)];
    this.usedWords.add(word);
    return word;
  }

  getDailySolution(): string {
    const epoch = new Date("2026-01-01").getTime();
    const now = Date.now();
    const dayIndex = Math.floor((now - epoch) / 86400000) % this.solutions.length;
    return this.solutions[dayIndex];
  }

  getSolutionCount(): number {
    return this.solutions.length;
  }

  getGuessCount(): number {
    return this.validGuesses.size;
  }
}

export const wordService = new WordService();
